#!/usr/bin/env bash

echo Running: arduino-cli compile . -p /dev/ttyAMC0 --fqbn arduino:samd:tian --verbose --export-binaries
arduino-cli compile . -p /dev/ttyAMC0 --fqbn arduino:samd:tian --verbose --export-binaries
printf "\n"

ls -lhv ./build
printf "\n"

tree ./build
printf "\n"
